### ISSUE TITLE
Привки по ДЗ 19

### ISSUE THREAD

**Issue by Dexter19** [NataMimoza/Light#15]
Чи мають рядки str1 та str2 однакову довжину. Перевірити на рівність (недбалу та строгу) рядки str1 та str2.
Тут можемо написати наступний код:
console.log(str1.length == str2.length); і отримаємо у відповідь true.
------------------------------------------------
повернути символ J рядка str3:
Ось так простіше console.log(str3[6]); // "J"
----------------------------------------------
4. Використовуючи індекс, отримати доступ до останнього символу рядка двома способами
Як варіант можемо використати метод простіше
// отримати доступ до останнього символу рядка
// використовуйте індекс length - 1:

let str4 = "Hello";
console.log(str4[str4.length -1]); // "o"

// використовуйте індекс length - 1:

console.log(str4[str4.length -1]); // "o"
------------------
Напишіть три варіанти функції lastChar, що повертає останній символ рядка
Врахував вашу відповідь, але можна ще реалізувати так:
function lastChar(str) {
    return str.split(-1);
}

console.log(lastChar(str4)); // "o"

function lastChar(str) {
    return str.charAt(str.length -1);
}

console.log(lastChar(str4)); // "o"

function lastChar(str) {
    return str.charAt(str.length -1);
}
console.log(lastChar(str4)); // "o"
-------------------------------
8. Маємо код. Напишіть функцію getFullName, що повертає результат: "Tom Cat"
Як варіант можна написати функцію з return
let firstName = "Tom";
let lastName = "Cat";

function getFullName (firstName, lastName) {
 return firstName + " " + lastName;
}
-----------------------------
10. Використовуючи функцію greeting, створити такий шаблон: <div><h1>Hello, Tom Cat!</h1></div>
Ще можна реалізувати ось так:
let template = (
 "<div>" +
 "<h1>"+greeting (firstName, lastName)+"</h1>" +
 "</div>"
);

console.log(template);
--------------------
12. Маємо наступний код
Перевірити, чи містить рядок значення 'look on'Б починаючи з 8-ї позиції
Отримаємо таку відповідь: sentence.includes('look on', 8); // false
-----------------------
Знайти індекс символу 'l', починаючи з 3-ї позиції
Відповідь коректна: sentence1.indexOf('l', 2); // 7
------------------------
Створити регулярний вираз, який призначений для перевірки імені користувача, що може містити цифри, літери у нижньому регістрі та символи - і _. Довжину імені користувача встановити від 8 до 16 знаків.
Можна проще ось так: 
let pattern = /^[a-z0-9_-]{8,16}$/;
let user = "tom_cat1";

const found = user.match(pattern);
console.log(found)
---------------------

**Comment by NataMimoza** [comment]
виправила
